spring.application.name=listing-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/listingdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

jwt.secret=${JWT_SECRET:dev-only-change-me-this-should-be-a-long-random-string}
jwt.expiration-ms=7200000