spring.application.name=review-service
server.port=${PORT:8085}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5435/reviewdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

jwt.secret=${JWT_SECRET:dev-only-change-me-this-should-be-a-long-random-string}
jwt.expiration-ms=7200000